https://bugs.python.org/issue16043
